---
- name: Install nginx
  become: true
  ansible.builtin.apt:
    name: nginx

- name: Remove default config
  become: true
  ansible.builtin.file:
    path: "{{ default_path }}"
    state: absent
  loop:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default
    - /etc/nginx/conf.d/default
  loop_control:
    loop_var: default_path

- name: Add NGINX configuration file
  become: true
  ansible.builtin.template:
    src: "{{ nginx_conf_src }}"
    dest: /etc/nginx/sites-enabled/{{ nginx_conf_dest }}
    mode: "0644"
  notify: Restart nginx
